name = "porra-fortilin-sync"
main = "workers/sync.ts"
compatibility_date = "2026-06-11"

[[d1_databases]]
binding = "DB"
database_name = "porra-fortilin"
database_id = "9b01ada1-d9ce-480e-a223-a3f96b69a3ee"

[vars]
OPENLIGADB_BASE_URL = "https://api.openligadb.de"
OPENLIGADB_LEAGUE_SHORTCUT = "wm26"
OPENLIGADB_SEASON = "2026"

[triggers]
crons = [
  "*/5 16-23 * * *",
  "*/5 0-3 * * *",
  "0 4-15 * * *"
]
