name = "porra-fortilin-sync"
main = "workers/sync.ts"
compatibility_date = "2026-06-11"

[[d1_databases]]
binding = "DB"
database_name = "porra-fortilin"
database_id = "9b01ada1-d9ce-480e-a223-a3f96b69a3ee"

[vars]
API_FOOTBALL_DAILY_BUDGET = "70"

[triggers]
crons = ["*/30 * * * *"]
