name = "porra-fortilin"
compatibility_date = "2026-06-11"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "porra-fortilin"
database_id = "9b01ada1-d9ce-480e-a223-a3f96b69a3ee"

[vars]
APP_NAME = "Porra Fortilin"
LEAGUE_NAME = "Fortilin"
API_FOOTBALL_DAILY_BUDGET = "70"
